// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 27 Apr 2019 01:29:59 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void KVAllCallback_5910e1e(void* context, int keybytes, char* key) {
	kVAllCallback5910E1E(context, keybytes, key);
}

void KVAllFunction_b6c66c05(int keybytes, char* key) {
	kVAllFunctionB6C66C05(keybytes, key);
}

void KVEachCallback_770981b9(void* context, int keybytes, char* key, int valuebytes, char* value) {
	kVEachCallback770981B9(context, keybytes, key, valuebytes, value);
}

void KVEachFunction_c45ee3a2(int keybytes, char* key, int valuebytes, char* value) {
	kVEachFunctionC45EE3A2(keybytes, key, valuebytes, value);
}

void KVGetCallback_6290ffe(void* context, int valuebytes, char* value) {
	kVGetCallback6290FFE(context, valuebytes, value);
}

void KVGetFunction_b57e6de5(int valuebytes, char* value) {
	kVGetFunctionB57E6DE5(valuebytes, value);
}

void KVStartFailureCallback_206ee003(void* context, char* engine, char* config, char* msg) {
	kVStartFailureCallback206EE003(context, engine, config, msg);
}

