// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Apr 2019 00:40:25 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package pmemkv_sys

/*
#cgo LDFLAGS: -lpmemkv -ltbb
#include "libpmemkv.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// KVStatus as declared in https://google.com/search?q=libpmemkv.h+KVStatus
type KVStatus int32

// KVStatus enumeration from https://google.com/search?q=libpmemkv.h+KVStatus
const ()
