// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 27 Apr 2019 15:23:07 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package pmemkv_sys

/*
#cgo LDFLAGS: -lpmemkv -ltbb
#include "libpmemkv.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// KVStatus as declared in pmemkv-go/libpmemkv.h:39
type KVStatus int32

// KVStatus enumeration from pmemkv-go/libpmemkv.h:39
const ()
