// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 01 May 2019 10:58:26 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package pmemkv provides Go bindings for pmemkv.
*/
package pmemkv_sys
