// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Apr 2019 00:40:25 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package pmemkv provides Go bindings for pmemkv.
*/
package pmemkv_sys
