// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 27 Apr 2019 16:36:20 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package pmemkv provides Go bindings for pmemkv.
*/
package pmemkv_sys
