// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sat, 27 Apr 2019 01:29:59 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package pmemkv_sys

/*
#cgo LDFLAGS: -lpmemkv -ltbb
#include "libpmemkv.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// KVAllCallback type as declared in pmemkv-go/libpmemkv.h:41
type KVAllCallback func(context unsafe.Pointer, keybytes int32, key string)

// KVAllFunction type as declared in pmemkv-go/libpmemkv.h:42
type KVAllFunction func(keybytes int32, key string)

// KVEachCallback type as declared in pmemkv-go/libpmemkv.h:43
type KVEachCallback func(context unsafe.Pointer, keybytes int32, key string, valuebytes int32, value string)

// KVEachFunction type as declared in pmemkv-go/libpmemkv.h:44
type KVEachFunction func(keybytes int32, key string, valuebytes int32, value string)

// KVGetCallback type as declared in pmemkv-go/libpmemkv.h:45
type KVGetCallback func(context unsafe.Pointer, valuebytes int32, value string)

// KVGetFunction type as declared in pmemkv-go/libpmemkv.h:46
type KVGetFunction func(valuebytes int32, value string)

// KVStartFailureCallback type as declared in pmemkv-go/libpmemkv.h:47
type KVStartFailureCallback func(context unsafe.Pointer, engine string, config string, msg string)

// KVEngineSys as declared in pmemkv-go/libpmemkv.h:135
type KVEngineSys C.KVEngine
