// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 30 Apr 2019 00:40:25 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package pmemkv_sys

/*
#cgo LDFLAGS: -lpmemkv -ltbb
#include "libpmemkv.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// KVAllCallback type as declared in https://google.com/search?q=libpmemkv.h+KVAllCallback
type KVAllCallback func(context unsafe.Pointer, keybytes int32, key string)

// KVEachCallback type as declared in https://google.com/search?q=libpmemkv.h+KVEachCallback
type KVEachCallback func(context unsafe.Pointer, keybytes int32, key string, valuebytes int32, value string)

// KVGetCallback type as declared in https://google.com/search?q=libpmemkv.h+KVGetCallback
type KVGetCallback func(context unsafe.Pointer, valuebytes int32, value string)

// KVStartFailureCallback type as declared in https://google.com/search?q=libpmemkv.h+KVStartFailureCallback
type KVStartFailureCallback func(context unsafe.Pointer, engine string, config string, msg string)

// KVEngineSys as declared in https://google.com/search?q=libpmemkv.h+KVEngine
type KVEngineSys C.KVEngine
